version: "3.7"

services:
  auth-api:
    container_name: auth-api
    image: auth-api
    build: .
    ports:
      - 8180:8180
    environment:
      - MODE=dev
    networks:
      - auth-api-net
      - auth-api-net-db
    volumes:
      - auth-api:/app/node_modules
      - .:/app

  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"
      networks:
      - auth-api-net
      - auth-api-net-db

networks:
  auth-api-net:
    name: auth-api-net
  
  auth-api-net-db:
    external:
      name: auth-api-net-db

volumes:
  auth-api:
    name: auth-api